"""add backtest trades and equity snapshots

Revision ID: 39ca258ac9a5
Revises: 030c07aead24
Create Date: 2026-04-05 18:29:41.371950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '39ca258ac9a5'
down_revision: Union[str, None] = '030c07aead24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=False),
    sa.Column('fill_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trade_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equity_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('snapshot_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equity_snapshots')
    op.drop_table('backtest_trades')
    # ### end Alembic commands ###